### ISSUE TITLE
Packet data type issues

### ISSUE THREAD

**Issue by k4l3b** [kamorin/DHCPig#15]
Before asking anything, allow me to grat you for this fine piece of art :)

(Please excuse my english, not my natural lang)
I'm testing different DHCP vectors, and wanted to try this app, but got a Python error when running it. I'm going to mess with the code, 'cos I'm guessing the problem is between 'pig.py' and fresh 'scappy' lib updates; but maybe you have it fixed.
The problem is when DHCPig tries to create a packet, possible passing a packet attribute value as a datatype that scapy does not like.
I'm testing in a internal VirtualBox network, using VMs btw.

The command:
$ ./pig.py --show-options enp0s3 > output.txt 2> error.txt

----[ output.txt ]----
[ -- ] [INFO] - using interface enp0s3
[DBG ] Thread 0 - (Sniffer) READY
[DBG ] Thread 1 - (Sender) READY
[--->] DHCP_Discover
[ ?? ] 		waiting for first DHCP Server response
[ ?? ] 		waiting for first DHCP Server response
[DBG ] ARP_Request 10.10.0.101 from 10.10.0.1
[ <- ] ARP_Response 10.10.0.101 : 08:00:27:7e:13:1f
[ ?? ] 		waiting for first DHCP Server response
[ -- ] timeout waiting on dhcp packet count 1
[ ?? ] 		waiting for first DHCP Server response
[ -- ] timeout waiting on dhcp packet count 2
[ ?? ] 		waiting for first DHCP Server response
[ ?? ] 		waiting for first DHCP Server response
[ -- ] timeout waiting on dhcp packet count 3
[ ?? ] 		waiting for first DHCP Server response
[ -- ] timeout waiting on dhcp packet count 4
[ ?? ] 		waiting for first DHCP Server response
[ ?? ] 		waiting for first DHCP Server response
[ ?? ] 		waiting for first DHCP Server response
[ ?? ] 		waiting for first DHCP Server response
[ ?? ] 		waiting for first DHCP Server response
[ ?? ] 		waiting for first DHCP Server response
[ ?? ] 		waiting for first DHCP Server response
[ ?? ] 		waiting for first DHCP Server response
[ ?? ] 		waiting for first DHCP Server response
[ ?? ] 		waiting for first DHCP Server response
[ ?? ] 		waiting for first DHCP Server response
[ ?? ] 		waiting for first DHCP Server response
[ ?? ] 		waiting for first DHCP Server response
[ -- ] [FAIL] No DHCP offers detected - aborting
[ -- ]  -----  ABORT ...  -----
[DBG ] Waiting for Thread 0 to die ...
[DBG ] Waiting for Thread 1 to die ...
----[ EOF ]----

----[ error.txt ]----
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "./pig.py", line 516, in run
    sendPacket(dhcp_discover)
  File "./pig.py", line 413, in sendPacket
    sendp(pkt, iface=conf.iface)
  File "/usr/local/lib/python2.7/dist-packages/scapy/sendrecv.py", line 315, in sendp
    verbose=verbose, realtime=realtime, return_packets=return_packets)
  File "/usr/local/lib/python2.7/dist-packages/scapy/sendrecv.py", line 276, in __gen_send
    s.send(p)
  File "/usr/local/lib/python2.7/dist-packages/scapy/arch/linux.py", line 551, in send
    return SuperSocket.send(self, x)
  File "/usr/local/lib/python2.7/dist-packages/scapy/supersocket.py", line 42, in send
    sx = raw(x)
  File "/usr/local/lib/python2.7/dist-packages/scapy/compat.py", line 72, in raw
    return x.__bytes__()
  File "/usr/local/lib/python2.7/dist-packages/scapy/packet.py", line 345, in __bytes__
    return self.build()
  File "/usr/local/lib/python2.7/dist-packages/scapy/packet.py", line 444, in build
    p = self.do_build()
  File "/usr/local/lib/python2.7/dist-packages/scapy/packet.py", line 429, in do_build
    pay = self.do_build_payload()
  File "/usr/local/lib/python2.7/dist-packages/scapy/packet.py", line 416, in do_build_payload
    return self.payload.do_build()
  File "/usr/local/lib/python2.7/dist-packages/scapy/packet.py", line 429, in do_build
    pay = self.do_build_payload()
  File "/usr/local/lib/python2.7/dist-packages/scapy/packet.py", line 416, in do_build_payload
    return self.payload.do_build()
  File "/usr/local/lib/python2.7/dist-packages/scapy/packet.py", line 429, in do_build
    pay = self.do_build_payload()
  File "/usr/local/lib/python2.7/dist-packages/scapy/packet.py", line 416, in do_build_payload
    return self.payload.do_build()
  File "/usr/local/lib/python2.7/dist-packages/scapy/packet.py", line 429, in do_build
    pay = self.do_build_payload()
  File "/usr/local/lib/python2.7/dist-packages/scapy/packet.py", line 416, in do_build_payload
    return self.payload.do_build()
  File "/usr/local/lib/python2.7/dist-packages/scapy/packet.py", line 426, in do_build
    pkt = self.self_build()
  File "/usr/local/lib/python2.7/dist-packages/scapy/packet.py", line 407, in self_build
    p = f.addfield(self, p, val)
  File "/usr/local/lib/python2.7/dist-packages/scapy/fields.py", line 521, in addfield
    return s + self.i2m(pkt, val)
  File "/usr/local/lib/python2.7/dist-packages/scapy/layers/dhcp.py", line 269, in i2m
    lval = [f.addfield(pkt,b"",f.any2i(pkt,val)) for val in lval]
  File "/usr/local/lib/python2.7/dist-packages/scapy/fields.py", line 841, in addfield
    s = self.field.addfield(pkt, s, v)
  File "/usr/local/lib/python2.7/dist-packages/scapy/fields.py", line 80, in addfield
    return s+struct.pack(self.fmt, self.i2m(pkt,val))
error: cannot convert argument to integer
----[ EOF ]----

The OS:
Linux testVM 4.9.0-6-amd64 #1 SMP Debian 4.9.82-1+deb9u3 (2018-03-02) x86_64 GNU/Linux

Others:

$ python -V
Python 2.7.13

$ pip show scapy
Name: scapy
Version: 2.4.0
Summary: Scapy: interactive packet manipulation tool
Home-page: http://www.secdev.org/projects/scapy
Author: Pierre LALET, Guillaume VALADON
Author-email: guillaume@valadon.net
License: GPLv2
Location: /usr/local/lib/python2.7/dist-packages
Requires:

**Comment by k4l3b** [comment]
After some debugging, I assume the problem is when crafting the DHCP package, specifically on code like this:

("param_req_list",chr(1),chr(121),chr(3),chr(6),chr(15),chr(119),chr(252),chr(95),chr(44),chr(46))

**Comment by k4l3b** [comment]
Fixed it. Replace the following:

1: Find this line (near line 608):
`dhcp_req = Ether(src=mymac,dst="ff:ff:ff:ff:ff:ff")/IP(src="0.0.0.0",dst="255.255.255.255")/UDP(sport=68,dport=67)/BOOTP(chaddr=[mac2str(localm)],xid=localxid,flags=0xFFFFFF)/DHCP(options=[("message-type","request"),("server_id",sip),("requested_addr",myip),("hostname",myhostname),("param_req_list","pad"),"end"])`

Replace with:
`#### Fix by k4l3b ####`
`# replaced ("param_req_list","pad") with ("param_req_list",0)`
`# The '0' is the equivalent of using DHCPRevOptions["pad"][0]`
`#dhcp_req = Ether(src=mymac,dst="ff:ff:ff:ff:ff:ff")/IP(src="0.0.0.0",dst="255.255.255.255")/UDP(sport=68,dport=67)/BOOTP(chaddr=[mac2str(localm)],xid=localxid,flags=0xFFFFFF)/DHCP(options=[("message-type","request"),("server_id",sip),("requested_addr",myip),("hostname",myhostname),("param_req_list","pad"),"end"])`
`dhcp_req = Ether(src=mymac,dst="ff:ff:ff:ff:ff:ff")/IP(src="0.0.0.0",dst="255.255.255.255")/UDP(sport=68,dport=67)/BOOTP(chaddr=[mac2str(localm)],xid=localxid,flags=0xFFFFFF)/DHCP(options=[("message-type","request"),("server_id",sip),("requested_addr",myip),("hostname",myhostname),("param_req_list",0),"end"])`
`#### End of Fix ######`

2: Find this line (near line 503):
`("param_req_list",chr(1),chr(121),chr(3),chr(6),chr(15),chr(119),chr(252),chr(95),chr(44),chr(46)),`

Replace with:
`#### Fix by k4l3b ####`
`# Replaced the chr(n) by it's numeric representation.`
`# Can be replaced by DHCPRevOptions[] as stated, but not all parameters are defined in scapy`
`# For a full list of 'em: https://www.iana.org/assignments/bootp-dhcp-parameters/bootp-dhcp-parameters.xhtml`
`#("param_req_list",chr(1),chr(121),chr(3),chr(6),chr(15),chr(119),chr(252),chr(95),chr(44),chr(46)),`
`('param_req_list',`
`    1,      # Subnet Mask                       DHCPRevOptions["subnet_mask"][0]`
`    121,    # Classless Satic Route`
`    3,      # Router                            DHCPRevOptions["router"][0]`
`    6,      # Domain Name Server                DHCPRevOptions["name_server"][0]`
`    15,     # Domain Name                       DHCPRevOptions["domain"][0]`
`    119,    # Domain Seach`
`    252,    # Private/Proxy Autodiscovery`
`    95,     # LDAP`
`    44,     # NetBIOS over TCP/IP Name Server   DHCPRevOptions["NetBIOS_server"][0]`
`    46      # NetBIOS over TCP/IP Node Type`
`),`
`#### End of Fix ######`

**Comment by sgeto** [comment]
I think I saw this before.

If I am not mistaken, then this is a bug in scapy, which they also already fixed.

Uninstall your version, try to install scapy from their Github repo and report this issue there if it's still exists.

:+1


"We are saddened by a bird's cry, but not for a fish's blood.
Blessed are those with voices."

-Mamoru Oshii

**Comment by kamorin** [comment]
can you both (@sgeto @k4l3b) verify DHCPig works with latest scapy on your system?

**Comment by Akkadius** [comment]
Latest version of scapy installed right from the repo shows the same result

*Workaround*

```pip install scapy==2.3.3```

**Comment by kamorin** [comment]
The plan is to update DHCPig to handle python3 in the short term.  At that point we will be moving scapy versions as well.
