### ISSUE TITLE
Random MAC

### ISSUE THREAD

**Issue by peppelinux** [kamorin/DHCPig#16]
https://github.com/kamorin/DHCPig/blob/9fd8df563b1f14fa4f736c9c28a56aa3d01cb92e/pig.py#L290

I use RandMAC() function from scapy.all

**Comment by kamorin** [comment]
good find, can you test with the latest scape and RandMac() removed?  If it works out can you create a PR?

thanks
Kevin

**Comment by peppelinux** [comment]
I used it here:
https://github.com/peppelinux/pyDHCPStarvator

It simply works
https://github.com/peppelinux/pyDHCPStarvator/blob/master/dhcp_discover.py

I also forked some bunch of your code, you'll easily find it

**Comment by sgeto** [comment]
I suggested this [back in March 2017](https://github.com/kamorin/DHCPig/pull/5).
Thinking back, I've misread your comment and reverted that change... 😞 
I thought you **didn't** like it.

**Comment by kamorin** [comment]
I'll move randomMAC() to scapy RandMAC() on our next revision.  Thanks again for the input
