### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by laulaufer** [kamorin/DHCPig#4]
Hello, 
i have this issue when lauching the tool with neighbors-scan-arp option.
I'm going to investigate more in this code, but if you have already an answer please reply me :)
the variable 'dhcpsip' seems None, don't know why ...
Thanks
Laurent

sudo ./pig.py --neighbors-scan-arp -r  eth0

WARNING: No route found for IPv6 destination :: (no default route?)
[ -- ] [INFO] - using interface eth0
[DBG ] Thread 0 - (Sniffer) READY
[DBG ] Thread 1 - (Sender) READY
[--->] DHCP_Discover
Traceback (most recent call last):
  File "./pig.py", line 690, in <module>
    main()
  File "./pig.py", line 673, in main
    if DO_ARP: neighbors()
  File "./pig.py", line 436, in neighbors
    net=dhcpsip+"/"+calcCIDR(subnet)
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
[--->] DHCP_Discover
[--->] DHCP_Discover
[--->] DHCP_Discover
[<---] DHCP_Offer   00:50:56:ee:02:90	192.168.174.254 IP: 192.168.174.134 for MAC=[de:ad:13:29:6c:96]
[--->] DHCP_Request 192.168.174.134
[<---] DHCP_Offer   00:50:56:ee:02:90	192.168.174.254 IP: 192.168.174.137 for MAC=[de:ad:0c:2b:96:b4]

**Comment by fnzv** [comment]
[ -- ] timeout waiting on dhcp packet count 3
[--->] DHCP_Discover
[--->] DHCP_Discover
[--->] DHCP_Discover
[--->] DHCP_Discover
[--->] DHCP_Discover
[--->] DHCP_Discover
[ ?? ]                  waiting for DHCP pool exhaustion...
[ -- ] timeout waiting on dhcp packet count 4
[ ?? ]                  waiting for DHCP pool exhaustion...
[ -- ] [INFO] waiting 8 to mass grat.arp!
Traceback (most recent call last):
  File "./pig.py", line 691, in <module>
    main()
  File "./pig.py", line 684, in main
    garp()
  File "./pig.py", line 484, in garp
    pool=Net(str(dhcpsip)+"/"+str(calcCIDR(subnet)))
  File "./pig.py", line 330, in calcCIDR
    bits.append(bin(int(c)))
ValueError: invalid literal for int() with base 10: 'None'


I had the same issue.. i tried to convert variables with str() but still not working 
I'm compiling with python 2.7..and last scapy version .. maybe he used older versions and didn't update the code

**Comment by MacTheZazou** [comment]
@kamorin same bug here... Any help?

**Comment by kamorin** [comment]
just merged 
https://github.com/kamorin/DHCPig/pull/6/commits/acafa2f2cf38564fbfcb03107ddf5eb86861bcd5
which should address the error.  Ping me if you still see it.
