### ISSUE TITLE
creating tags (or github releases)

### ISSUE THREAD

**Issue by pthierry38** [kamorin/DHCPig#9]
Hi !

I'm currently packaging the dhcpig tool for Debian, but i can't activate the uscan subsystem (which tracks updates in the mainstream project) without having a tag or a github release to catch.
Is it possible to support versions (through tags on master) or using the github releases ?

Thanks!

**Comment by kamorin** [comment]
all set, version 1.5 shipped.

https://github.com/kamorin/DHCPig/releases/tag/1.5
